name: sync

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 */8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-aliyun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # 3. 运行 go 代码
      - name: Run code
        run: |
          export MIRROR=`cat mirror.txt`
          go run main.go --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_TOKEN }} --repository=${{ secrets.DOCKER_REPOSITORY }} --content='$MIRROR' --maxContent=20 --outputPath=output.sh
          cat output.sh