name: sync

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 */8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-aliyun:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    # 3. 运行 go 代码
    - name: Run code
      run: |
        go run main.go --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_TOKEN }} --repository=${{ secrets.DOCKER_REPOSITORY }} --content='`cat mirror.txt`' --maxContent=20 --outputPath=output.sh
        cat output.sh